use_frameworks!

platform :ios, '10.0'

target 'DeclarativeUIKit_Example' do
  pod 'DeclarativeUIKit', :path => '../'
  pod 'DeclarativeUIKit/Rx', :path => '../'
  pod 'DeclarativeUIKit/ApplyStyleKit', :path => '../'
  pod 'DeclarativeUIKit/Combine', :path => '../'
  pod 'DeclarativeUIKit/SnapKit', :path => '../'
  pod 'SnapKit'

  target 'DeclarativeUIKit_Tests' do
    inherit! :search_paths

    
  end
end
