
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '10.0'

target 'DeclarativeUIKit_Example' do
  pod 'EGDeclarativeUIKit', :path => '../'
  pod 'EGDeclarativeUIKit/Ext', :path => '../'
  pod 'EGDeclarativeUIKit/Rx', :path => '../'
  pod 'EGDeclarativeUIKit/ApplyStyleKit', :path => '../'
  pod 'EGDeclarativeUIKit/Combine', :path => '../'
  pod 'EGDeclarativeUIKit/SnapKit', :path => '../'
  pod 'EGDeclarativeUIKit/Chainable', :path => '../'
  pod 'SnapKit'

  target 'DeclarativeUIKit_Tests' do
    inherit! :search_paths

    
  end
end
